#!/usr/bin/env bash

TEST_VALUE=$1

echo "DAEDALUS_CONFIG_MODULES_PATH = $DAEDALUS_CONFIG_MODULES_PATH"
echo "DAEDALUS_CONFIG_MODULE_PATH = $DAEDALUS_CONFIG_MODULE_PATH"
echo "DAEDALUS_STATE_MODULE_PATH = $DAEDALUS_STATE_MODULE_PATH"
echo "DAEDALUS_MODULE_NAME = $DAEDALUS_MODULE_NAME"
echo "DAEDALUS_CONFIG_PATH = $DAEDALUS_CONFIG_PATH"
echo "DAEDALUS_PROJECT = $DAEDALUS_PROJECT"
echo "DAEDALUS_PROJECT_PATH = $DAEDALUS_PROJECT_PATH"
echo "DAEDALUS_GLOBAL_STATE_PATH = $DAEDALUS_GLOBAL_STATE_PATH"
echo "DAEDALUS_STATE_PATH = $DAEDALUS_GLOBAL_STATE_PATH"
echo "DAEDALUS_STATE_MODULES_PATH = $DAEDALUS_STATE_MODULES_PATH"
echo "DAEDALUS_MODULE_COMMAND = $DAEDALUS_MODULE_COMMAND"
echo "DAEDALUS_MODULE_NAMESPACE = $DAEDALUS_MODULE_NAMESPACE"
echo "DAEDALUS_CONFIG_PLUGIN_NAME = $DAEDALUS_CONFIG_PLUGIN_NAME"

echo "TEST_VALUE = $TEST_VALUE"

